### PR TITLE
Onclick on cells

### LINKED ISSUE #19: table onclick
Hi, how can I create a click event for each cell?
i want to open activity when click on cell , so can edit data

### PR DESCRIPTION
**Pull request by gwabstech**
Added onclick on the cells each sell created is clickable kindly review and if needed any changes or fixing let me know

### CODE REVIEW

**Comment by gwabstech** [comment]
as you said in my last PR

**Comment by gwabstech** [comment]
Great!

**Comment by Breens-Mbaka** [comment]
LGTM I'll proceed to merge it to the master branch. Thank you for your contribution @gwabstech

**Comment by gwabstech** [comment]
Awesome, thank you so much!

**Comment by gwabstech** [comment]
How is the protest in Kenya hope it's getting better

**Comment by Breens-Mbaka** [comment]
Hi @gwabstech when I go to the second row the index starts again at zero instead of continuing to 5,6,7. I think that's how it should work. Check the video recording below and revert

https://github.com/user-attachments/assets/44a20f3f-6cb2-4dd2-932e-3f0ee7f03704

**Comment by gwabstech** [comment]
Yes sure but am working on a specific cell click so that each cell can be
clicked indepently. For now that's the default case it start from zero when
you go to second row

**Comment by Breens-Mbaka** [comment]
Okay that's fine, but how will someone know they are clicking on a cell in the second row and not the first row ?

**Comment by gwabstech** [comment]
Great point let me review and get back to you tonight

**Pull request merged**
